### ISSUE TITLE
Tela de Avisos

### ISSUE THREAD

**Issue by DanielBranquinho** [Maua-Dev/System_Maua_Front#25]
Criar tela de avisos, referente ao menu "Help". 
Criar tela do aviso expandida, vide segunda imagem anexada.

- [x] Layout geral da primeira tela
- [x] Layout geral da segunda tela
- [x] Box dos comunicados
- [x] Data do comunicado, sem a funcionalidade integrada de calendário.
- [x] Checkbox para cada aviso

<img width="375" alt="documento de atividades)-1" src="https://user-images.githubusercontent.com/71044536/126683887-e19fac68-39e4-484c-8df6-0d55bc03bfab.png">
<img width="375" alt="documento de atividades)" src="https://user-images.githubusercontent.com/71044536/126683902-003e976f-6132-46df-b8b3-afae5f40fe01.png">

**Comment by FerdOliveira** [comment]
![image](https://user-images.githubusercontent.com/79317347/128448766-201bbce5-4eb8-4719-ac3c-f3f5f8a8fb7b.png)
