### ISSUE TITLE
Bottom Bar

### ISSUE THREAD

**Issue by DanielBranquinho** [Maua-Dev/System_Maua_Front#5]
Criar bottom bar com funcionalidade de subida e descida. Apresentando apenas ícones nos devidos lugares.

- [x] Layout da bottom bar com ícones
- [x] Funcionalidade de subida/descida

 
<img width="375" alt="Home" src="https://user-images.githubusercontent.com/71044536/124943321-c5db0400-dfe2-11eb-8dd1-c056ab747842.png">

**Comment by GabrielGodoy01** [comment]
![image](https://user-images.githubusercontent.com/61150821/125703908-143d697d-6db5-41a2-bf4c-f0ecedbad8bb.png)
