### ISSUE TITLE
Tela de Login

### ISSUE THREAD

**Issue by DanielBranquinho** [Maua-Dev/System_Maua_Front#6]
Criar tela de login sem a funcionalidade de "Esqueci minha senha". 

- [x] Layout geral da tela
- [x] Funcionalidade de manter-se conectado 
- [x] Validação de email
- [x] Mostrar na tela a validação errada da senha/email

- [x] Teste Unitário

<img width="375" alt="Login" src="https://user-images.githubusercontent.com/71044536/124944276-8e208c00-dfe3-11eb-9009-c0a29ed39057.png">

**Comment by Gustavo-CRS** [comment]
![image](https://user-images.githubusercontent.com/51282187/129793904-3bc8220c-bbc4-4e7f-91a2-2dd9cd8d55ee.png)
