### ISSUE TITLE
Tela de splash

### ISSUE THREAD

**Issue by DanielBranquinho** [Maua-Dev/System_Maua_Front#7]
Criar tela de splash

- [x] Configurar como inicial e redirecionar após 2 segundos
- [x] Layout da tela

<img width="375" alt="Splash" src="https://user-images.githubusercontent.com/71044536/124946820-b6a98580-dfe5-11eb-96a2-af04f74a720c.png">

**Comment by FerdOliveira** [comment]
![image](https://user-images.githubusercontent.com/79317347/126235877-53bdb005-a500-4edc-9a66-f995ecdc064e.png)
